// Professional style labels without emojis

export const SECTION_STYLES = {
  'BANNER_SECTION': 'Banner Section - Full width banners',
  'SLIDE_SECTION': 'Slide Section - Horizontal scrolling',
  'TAB_SECTION': 'Tab Section - Tabbed content',
  'TI_SECTION': 'Tab Items Section - Icon tabs',
  'TI_SECTION_V2': 'Tab Items V2 - Enhanced icon tabs',
  'REC_SECTION': 'Recommended Section - Product recommendations',
  'VOC_SECTION': 'Reviews Section - Customer testimonials',
  'VIDEO_SECTION': 'Video Section - Video content',
  'STORE_SECTION': 'Store Section - Shop categories',
  'FOOTER_SECTION': 'Footer Section - Bottom navigation',
  'GRID_SECTION': 'Grid Section - Grid layout',
  'RECENTLY_VIEWED_SECTION': 'Recently Viewed - User history',
  'LANDING_PAGE_BANNER_SECTION': 'Landing Banner - Hero section',
  'IMAGE_WITH_TEXT_SECTION': 'Image + Text - Content blocks',
  'CATEGORY_TABBING_SECTION': 'Category Tabs - Category navigation',
  'CATEGORY_STYLE_SECTION': 'Category Style - Category cards',
  'IMAGE_WITH_TEXT_BREAKER_SECTION': 'Image + Text Breaker - Section divider',
  'BY_PRICE_SECTION': 'By Price - Price range filters',
  'SHOP_LOOK_SECTION': 'Shop Look - Complete outfits',
  'BY_OCCASION_SECTION': 'By Occasion - Event-based shopping',
  'TOP_PRODUCTS_LIST_SECTION': 'Top Products - List view',
  'COLLECTION_VIDEO_SECTION': 'Collection Video - Video gallery',
  'CATEGORY_TAB_SECTION': 'Category Tab - Tab navigation',
  'PRODUCTS_WITH_TABS_SECTION': 'Products with Tabs - Filtered products',
  'PRODUCTS_WITHOUT_TABS_SECTION': 'Products - Simple product list',
  'CX_REVIEW_SECTION': 'Customer Reviews - Detailed reviews',
  'CIR_SECTION': 'Circular Section - Round icons',
};

export const COLLECTION_STYLES = {
  'BANNER_COLLECTION': 'Banner - Full width image banners',
  'SLIDER_COLLECTION': 'Slider - Horizontal scrolling cards',
  'TAB_COLLECTION': 'Tab - Tabbed content',
  'TI_COLLECTION': 'Tab Items - Icon-based tabs',
  'TI_COLLECTION_V2': 'Tab Items V2 - Enhanced tabs',
  'REC_COLLECTION': 'Recommended - Product cards with ratings',
  'VIDEO_COLLECTION': 'Video - Video player',
  'STORE_COLLECTION': 'Store - Category/store cards',
  'FOOTER_COLLECTION': 'Footer - Bottom navigation items',
  'VOC_COLLECTION': 'Reviews - Customer testimonials',
  'GRID_COLLECTION': 'Grid - 2-column grid layout',
  'RECENTLY_VIEWED_COLLECTION': 'Recently Viewed - User history',
  'LANDING_PAGE_BANNER_COLLECTION': 'Landing Banner - Hero banners',
  'IMAGE_WITH_TEXT_COLLECTION': 'Image + Text - Image with description',
  'CATEGORY_TABBING_COLLECTION': 'Category Tabs - Category navigation',
  'CATEGORY_STYLE_COLLECTION': 'Category Style - Category cards',
  'IMAGE_WITH_TEXT_BREAKER_COLLECTION': 'Image + Text Breaker - Content divider',
  'BY_PRICE_COLLECTION': 'By Price - Price range cards',
  'SHOP_LOOK_COLLECTION': 'Shop Look - Complete outfit cards',
  'BY_OCCASION_COLLECTION': 'By Occasion - Event shopping',
  'TOP_PRODUCTS_LIST_COLLECTION': 'Top Products - Horizontal list',
  'COLLECTION_VIDEO_COLLECTION': 'Collection Video - Video items',
  'CATEGORY_TAB_COLLECTION': 'Category Tab - Tab navigation',
  'PRODUCTS_WITH_TABS_COLLECTION': 'Products with Tabs - Filtered view',
  'PRODUCTS_WITHOUT_TABS_COLLECTION': 'Products - Simple list',
  'CX_REVIEW_COLLECTION': 'Customer Reviews - Review cards',
  'CIR_COLLECTION': 'Circular - Round icon items',
  'TAB_COLLECTION_NEW_ARRIVAL_NO_BACKGROUND': 'Tab New Arrival (No BG)',
  'TAB_COLLECTION_NEW_ARRIVAL': 'Tab New Arrival',
};

export const ITEM_STYLES = {
  'BANNER_COLLECTION_ITEM': 'Banner Item - Full width banner',
  'SLIDER_COLLECTION_ITEM': 'Slider Item - Product card',
  'REC_COLLECTION_ITEM': 'Product Card - With price & rating',
  'CIR_COLLECTION_ITEM': 'Circular Item - Round icon',
  'TI_COLLECTION_ITEM': 'Tab Item - Icon tab',
  'TI_COLLECTION_ITEM_V2': 'Tab Item V2 - Enhanced tab',
  'VIDEO_COLLECTION_ITEM': 'Video Item - Video player',
  'STORE_COLLECTION_ITEM': 'Store Item - Category card',
  'FOOTER_COLLECTION_ITEM': 'Footer Item - Nav button',
  'VOC_COLLECTION_ITEM': 'Review Item - Testimonial card',
  'GRID_COLLECTION_ITEM': 'Grid Item - Grid card',
  'TAB_COLLECTION_ITEM': 'Tab - Tab button',
  'RECENTLY_VIEWED_COLLECTION_ITEM': 'Recently Viewed - History item',
  'LANDING_PAGE_BANNER_COLLECTION_ITEM': 'Landing Banner - Hero item',
  'IMAGE_WITH_TEXT_COLLECTION_ITEM': 'Image + Text - Content card',
  'CATEGORY_TABBING_COLLECTION_ITEM': 'Category Tab - Category item',
  'CATEGORY_STYLE_COLLECTION_ITEM': 'Category - Category card',
  'IMAGE_WITH_TEXT_BREAKER_COLLECTION_ITEM': 'Image + Text Breaker',
  'BY_PRICE_COLLECTION_ITEM': 'By Price - Price card',
  'SHOP_LOOK_COLLECTION_ITEM': 'Shop Look - Outfit card',
  'BY_OCCASION_COLLECTION_ITEM': 'By Occasion - Event card',
  'TOP_PRODUCTS_LIST_COLLECTION_ITEM': 'Top Product - List item',
  'COLLECTION_VIDEO_COLLECTION_ITEM': 'Video - Video item',
  'CATEGORY_TAB_COLLECTION_ITEM': 'Category Tab Item',
  'PRODUCTS_WITH_TABS_COLLECTION_ITEM': 'Product with Tabs',
  'PRODUCTS_WITHOUT_TABS_COLLECTION_ITEM': 'Product Item',
  'CX_REVIEW_COLLECTION_ITEM': 'Customer Review',
  'REC_COLLECTION_ITEM_NEW_ARRIVAL': 'New Arrival Product',
};
